### ISSUE TITLE
Error when you do 'pip install r6sapi'

### ISSUE THREAD

**Issue by UltimateDucc** [billy-yoyo/RainbowSixSiege-Python-API#45]
Error when typing 'pip install r6sapi'

Output/Error:

 `ERROR: Command errored out with exit status 1:
   command: 'c:\users\zacis\appdata\local\programs\python\python37\python.exe' 'c:\users\zacis\appdata\local\programs\python\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\zacis\AppData\Local\Temp\pip-build-env-f23exrcu\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
      import locale
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\locale.py", line 16, in <module>
      import re
    File "c:\users\zacis\appdata\local\programs\python\python37\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\zacis\appdata\local\programs\python\python37\python.exe' 'c:\users\zacis\appdata\local\programs\python\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\zacis\AppData\Local\Temp\pip-build-env-f23exrcu\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.`

NOTE: My PIP and Python work fine; this is the only error I've had installing a package.

**Comment by billy-yoyo** [comment]
Is there a file called "enum.py" in your working directory? Looks like that important is being overriden

**Comment by UltimateDucc** [comment]
Yes there is, is there a way to still install it?

**Comment by billy-yoyo** [comment]
Install from a different folder

**Comment by UltimateDucc** [comment]
I had to `pip uninstall enum34`
