### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by LaughOutQuiet** [billy-yoyo/RainbowSixSiege-Python-API#9]
```Ignoring exception in command r6
Traceback (most recent call last):
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Matthew\Desktop\Projects\Python\Discord\Bots\Series\Laugh (All in one)\CogStats.py", line 66, in r6
    player = await auth.get_player(user, api.Platforms.UPLAY)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\r6sapi\r6sapi.py", line 522, in get_player
    results = yield from self.get_players(name=name, platform=platform, uid=uid)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\r6sapi\r6sapi.py", line 488, in get_players
    data = yield from self.get("https://public-ubiservices.ubi.com/v2/profiles?nameOnPlatform=%s&platformType=%s" % (parse.quote(name), parse.quote(platform)))
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\r6sapi\r6sapi.py", line 394, in get
    raise FailedToConnect
r6sapi.r6sapi.FailedToConnect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FailedToConnect: 
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06962970>```

I get this error when i run my command? any idea on whats wrong and how to fix?

**Comment by NG-Bullseye** [comment]
Same problem here

Traceback (most recent call last):
  File "C:/Users/leona/OneDrive/Programme/Telegram-Bot-master/tele_news.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "C:\Users\leona\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:/Users/leona/OneDrive/Programme/Telegram-Bot-master/tele_news.py", line 9, in run
    player = yield from auth.get_player("NG-Loki", api.Platforms.UPLAY)
  File "C:\Users\leona\AppData\Local\Programs\Python\Python36\lib\site-packages\r6sapi\r6sapi.py", line 522, in get_player
    results = yield from self.get_players(name=name, platform=platform, uid=uid)
  File "C:\Users\leona\AppData\Local\Programs\Python\Python36\lib\site-packages\r6sapi\r6sapi.py", line 488, in get_players
    data = yield from self.get("https://public-ubiservices.ubi.com/v2/profiles?nameOnPlatform=%s&platformType=%s" % (parse.quote(name), parse.quote(platform)))
  File "C:\Users\leona\AppData\Local\Programs\Python\Python36\lib\site-packages\r6sapi\r6sapi.py", line 394, in get
    raise FailedToConnect
r6sapi.r6sapi.FailedToConnect
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000013C2DADE710>

**Comment by NG-Bullseye** [comment]
I only get that exception when I call billy-yoyo's example program from a different class. If I run the script by itself it works.

**Comment by billy-yoyo** [comment]
Three things that might be wrong:

- max_connect_retries has been set to 0 (e.g. `auth = r6sapi.Auth(..., max_connect_retries=0)`)
- your email/password is incorrect
- you're being rate-limited by ubisoft

Is the error happening every time, or does it sometimes work?
The last one is unlikely, unless you've been spamming requests a lot.

**Comment by LaughOutQuiet** [comment]
@billy-yoyo It has not been happening very often and it tends to happen after i use a few commands in a shorter time period, over 3 minutes i used 10 commands and i got the error after i successfully executed the 10 commands, sorry for responding late, I don't usually check github (kinda forgot I had it) but i will implement the max_connect_retries

**Comment by billy-yoyo** [comment]
Closing as the issue was fixed, will consider adding better error reporting later so it's more obvious why you're failing to connect, if possible.
